### ISSUE TITLE
请问用nginx怎么部署？

### ISSUE THREAD

**Issue by SunnyTuZi** [vok123/vue3-ts-vite-ssr-starter#10]

**Comment by SunnyTuZi** [comment]
![Uploading 1710383916194.jpg…]()

**Comment by SunnyTuZi** [comment]
![1710383916194](https://github.com/vok123/vue3-ts-vite-ssr-starter/assets/23352650/2b5c549c-16d0-4807-9793-406a50dce2b8)

**Comment by vok123** [comment]
你当前的nginx配置是怎么样的？

**Comment by SunnyTuZi** [comment]
您好，这是我的nginx配置，感谢你的回复
![1710384446236](https://github.com/vok123/vue3-ts-vite-ssr-starter/assets/23352650/0b13d04c-f868-491d-bfc0-353327e79283)

**Comment by vok123** [comment]
1. 44行改成 proxy_pass http://127.0.0.1:80;
2. 删除 45 46行

你现在的问题是： nginx代理的只是静态文件，本来这个项目就是服务器渲染，不应该直接代理静态资源，应该用server端render出来的html。如果你是有意将其他静态资源放cdn或者放其他服务器， 可以参考一下vite配置， 将Vite 的 base 配置为域名前缀。

**Comment by SunnyTuZi** [comment]
你好，server端的打包结果没有html文件。

**Comment by vok123** [comment]
启动服务端请求到127.0.0.1:80就会返回html。。。 你得理解服务器渲染概念

**Comment by SunnyTuZi** [comment]
好的，谢谢哈。
