### ISSUE TITLE
Cannot run "npm run dev"

### ISSUE THREAD

**Issue by AnonimBella** [vok123/vue3-ts-vite-ssr-starter#4]
Thank you for your wonderfull repo, I got stuck when I run "npm run dev"
I got these error:
![image](https://user-images.githubusercontent.com/13130920/144793040-87c0aba7-5b7a-442e-a963-498714c5c2e1.png)
Is it because vite or the config ? Btw, I'm new in vite.
Thanks before!

**Comment by vok123** [comment]
Hey bro, can you delete`node_modules` and `yarn install` again?

**Comment by AnonimBella** [comment]
> Hey bro, can you delete`node_modules` and `yarn install` again?

I delete the modules and yarn install again, the error still same:
![image](https://user-images.githubusercontent.com/13130920/144798669-2050138e-9bed-4884-b584-261916261224.png)

**Comment by vok123** [comment]
What is your`node` version? I use `v14+` and it’s okay. By the way, the`Typescript` version remains less than `4.5.0`

**Comment by AnonimBella** [comment]
My node version is 12, I'll try to upgrade first

**Comment by AnonimBella** [comment]
> What is your`node` version? I use `v14+` and it’s okay. By the way, the`Typescript` version remains less than `4.5.0`

it works! The cause is node version need to upgrade. Thanks you!
