### ISSUE TITLE
大佬，打包之后如何运行？

### ISSUE THREAD

**Issue by tanwongo** [vok123/vue3-ts-vite-ssr-starter#7]
[
<img width="154" alt="WX20220711-173315@2x" src="https://user-images.githubusercontent.com/7060885/178234855-e7176ea6-437f-49f9-b8ab-d4126a5c1bc9.png">

**Comment by tanwongo** [comment]
运行 npm run build 后 有个dist文件夹 。
里面有client和server 2个文件夹，请问如何该运行呢？

**Comment by vok123** [comment]
`npm run serve`
